# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

apiVersion: 1

datasources:
  - name: Elastic
    type: elasticsearch
    url: https://es01:9200/
    basicAuth: true
    basicAuthUser: elastic
    basicAuthPassword: elastic
    editable: true
    skipTlsVerify: true
    jsonData:
      index: '.ds-*'
      interval: daily
      timeField: '@timestamp'
      
      